export interface ContentItem {
  no: number;
  tanggal: string;
  jenis: string;
  tujuan: string;
  hookType: string;
  headline: string;
  body: string;
  caption: string;
  format: string;
  referensi: string;
  visual: string;
  keterangan: string;
  primaryAssetType?: string;
  recommendedAssetTypes?: string[];
  assetTypeReason?: string;
  carousel_plan?: any;
  isGrowth?: boolean;
  projectId?: string;
  project_id?: string;
  content_item_id?: string;
  cta?: string;
  productionProgress?: import('@/lib/content-contract').ProductionProgress;
}

export interface ConfigDataProps {
  coreTopic: string;
  setCoreTopic: (val: string) => void;
  startDate: string;
  setStartDate: (val: string) => void;
  skipDays: string[];
  setSkipDays: (val: string[] | ((prev: string[]) => string[])) => void;
  toggleSkipDay: (day: string) => void;
  gender: string;
  setGender: (val: string) => void;
  ageRange: [number, number];
  setAgeRange: (val: [number, number]) => void;
  formats: string[];
  setFormats: (val: string[] | ((prev: string[]) => string[])) => void;
  toggleFormat: (fmt: string) => void;
  carouselSlides: number;
  setCarouselSlides: (val: number) => void;
  reelsDuration: string;
  setReelsDuration: (val: string) => void;
  ratio: { tofu: number; mofu: number; bofu: number };
  setRatio: (val: { tofu: number; mofu: number; bofu: number } | ((prev: { tofu: number; mofu: number; bofu: number }) => { tofu: number; mofu: number; bofu: number })) => void;
  hasUserFunnelOverride?: boolean;
  setHasUserFunnelOverride?: (val: boolean) => void;
  hasUserCtaOverride?: boolean;
  setHasUserCtaOverride?: (val: boolean) => void;
  hasUserHookOverride?: boolean;
  setHasUserHookOverride?: (val: boolean) => void;
  hasUserFormulaOverride?: boolean;
  setHasUserFormulaOverride?: (val: boolean) => void;
  hasUserCoreTopicOverride?: boolean;
  setHasUserCoreTopicOverride?: (val: boolean) => void;
  formatRatio: Record<string, number>;
  setFormatRatio: (val: Record<string, number> | ((prev: Record<string, number>) => Record<string, number>)) => void;
  selectedVoices: string[];
  setSelectedVoices: (val: string[] | ((prev: string[]) => string[])) => void;
  toggleVoice: (v: string) => void;
  hookMix: { type: string; percentage?: number }[];
  setHookMix: (val: { type: string; percentage?: number }[] | ((prev: { type: string; percentage?: number }[]) => { type: string; percentage?: number }[])) => void;
  updateHookMix: (index: number, field: string, val: any) => void;
  selectedFormula: string;
  setSelectedFormula: (val: string) => void;
  referenceType: string;
  setReferenceType: (val: string) => void;
  selectedCTAs: string[];
  setSelectedCTAs: (val: string[] | ((prev: string[]) => string[])) => void;
  toggleCTA: (cta: string) => void;
  isFastMode: boolean;
  setIsFastMode: (val: boolean) => void;
  generateContent: () => void;
  editableContext?: any;
  sharedContentContext?: any;
  strategyBlueprint?: any;
  selectedProject?: string;
  brandContext?: any;
  connectionStatus?: string;
}
